const config=window.JABARI_CONFIG||{};const {createClient}=window.supabase;const supabase=createClient(config.SUPABASE_URL,config.SUPABASE_KEY);const $=id=>document.getElementById(id);const slugify=v=>String(v||"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");let categories=[],autopilot=null;
function msg(t,e=false){$("statusMsg").textContent=t||"";$("statusMsg").style.color=e?"#b42318":"#16794c"}function loginMsg(t){$("loginMsg").textContent=t||""}function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
async function isAdmin(){const {data:{user}}=await supabase.auth.getUser();if(!user)return false;const {data,error}=await supabase.from("media_admins").select("user_id").eq("user_id",user.id).maybeSingle();if(error)throw error;return!!data}
async function loadCategories(){const {data,error}=await supabase.from("media_categories").select("id,name,slug").order("name");if(error)throw error;categories=data||[];const h=categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("");$("articleCategory").innerHTML=h;$("topicCategory").innerHTML=`<option value="">No category</option>${h}`}
async function loadArticles(){const {data,error}=await supabase.from("media_articles").select("id,title,slug,status,article_type,published_at,updated_at,media_categories(name)").order("created_at",{ascending:false});if(error)throw error;const a=data||[];$("publishedCount").textContent=a.filter(x=>x.status==="published").length;$("draftCount").textContent=a.filter(x=>x.status==="draft"||x.status==="review").length;$("articles").innerHTML=a.length?a.map(x=>`<div class="articleRow"><div class="articleMeta"><strong>${esc(x.title)}</strong><small>${esc(x.media_categories?.name||"Uncategorised")} · ${esc(x.status)}</small></div><button class="secondary editArticle" data-id="${x.id}">Edit</button></div>`).join(""):"<p class='muted'>No articles yet.</p>";document.querySelectorAll(".editArticle").forEach(b=>b.onclick=()=>editArticle(b.dataset.id))}
async function loadTopics(){const {data,error}=await supabase.from("media_topics").select("id,topic,status,priority,media_categories(name)").order("created_at",{ascending:false});if(error)throw error;const a=data||[];$("topicCount").textContent=a.filter(x=>x.status==="queued").length;$("topics").innerHTML=a.length?a.map(x=>`<div class="topic"><div><strong>${esc(x.topic)}</strong><div class="muted">${esc(x.media_categories?.name||"No category")} · ${esc(x.status)}</div></div><button class="secondary deleteTopic" data-id="${x.id}">Delete</button></div>`).join(""):"<p class='muted'>No topics yet.</p>";document.querySelectorAll(".deleteTopic").forEach(b=>b.onclick=()=>deleteTopic(b.dataset.id))}
async function loadAutopilot(){const {data,error}=await supabase.from("media_autopilot").select("*").eq("id",1).single();if(error)throw error;autopilot=data;renderAutopilot()}
function renderAutopilot(){const on=!!autopilot.enabled;$("autoState").textContent=on?"ON":"OFF";$("autoLabel").textContent=on?"Autopilot is ON":"Autopilot is OFF";$("autoDescription").textContent=on?"Automation is allowed to run.":"No automatic publishing will run.";$("autoBtn").textContent=on?"Turn OFF":"Turn ON";$("autoBtn").className=on?"secondary":"danger";$("autoMode").value=autopilot.mode;$("autoFrequency").value=autopilot.publishing_frequency}
async function editArticle(id){const {data,error}=await supabase.from("media_articles").select("*").eq("id",id).single();if(error)return msg(error.message,true);$("articleId").value=data.id;$("articleTitle").value=data.title||"";$("articleSlug").value=data.slug||"";$("articleExcerpt").value=data.excerpt||"";$("articleCategory").value=data.category_id||categories[0]?.id||"";$("articleType").value=data.article_type||"article";$("articleImage").value=data.featured_image||"";$("articleContent").value=data.content||"";$("seoTitle").value=data.seo_title||"";$("metaDescription").value=data.meta_description||"";window.scrollTo({top:0,behavior:"smooth"})}
function resetArticle(){$("articleId").value="";$("articleTitle").value="";$("articleSlug").value="";$("articleExcerpt").value="";$("articleCategory").value=categories[0]?.id||"";$("articleType").value="article";$("articleImage").value="";$("articleContent").value="";$("seoTitle").value="";$("metaDescription").value=""}
$("loginForm").onsubmit=async e=>{e.preventDefault();loginMsg("Signing in...");const {error}=await supabase.auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});if(error)return loginMsg(error.message);await boot()};$("logoutBtn").onclick=async()=>{await supabase.auth.signOut();location.reload()};$("newArticleBtn").onclick=resetArticle;
$("articleForm").onsubmit=async e=>{e.preventDefault();const status=e.submitter?.dataset.status||"draft";const title=$("articleTitle").value.trim();if(!title)return;const p={title,slug:slugify($("articleSlug").value)||slugify(title),excerpt:$("articleExcerpt").value.trim(),content:$("articleContent").value,category_id:$("articleCategory").value||null,author_id:null,featured_image:$("articleImage").value.trim()||null,status,article_type:$("articleType").value,seo_title:$("seoTitle").value.trim()||title,meta_description:$("metaDescription").value.trim()||$("articleExcerpt").value.trim(),published_at:status==="published"?new Date().toISOString():null,updated_at:new Date().toISOString()};msg("Saving...");const r=$("articleId").value?await supabase.from("media_articles").update(p).eq("id",$("articleId").value):await supabase.from("media_articles").insert(p);if(r.error)return msg(r.error.message,true);msg(status==="published"?"Article published.":"Draft saved.");resetArticle();await loadArticles()};
$("topicForm").onsubmit=async e=>{e.preventDefault();const topic=$("topicInput").value.trim();if(!topic)return;const {error}=await supabase.from("media_topics").insert({topic,category_id:$("topicCategory").value||null,status:"queued"});if(error)return msg(error.message,true);$("topicInput").value="";msg("Topic added.");await loadTopics()};
async function deleteTopic(id){if(!confirm("Delete this topic?"))return;const {error}=await supabase.from("media_topics").delete().eq("id",id);if(error)return msg(error.message,true);await loadTopics()}
$("autoBtn").onclick=async()=>{const {data,error}=await supabase.from("media_autopilot").update({enabled:!autopilot.enabled,updated_at:new Date().toISOString()}).eq("id",1).select("*").single();if(error)return msg(error.message,true);autopilot=data;renderAutopilot();msg(autopilot.enabled?"Autopilot turned ON.":"Autopilot turned OFF.")};
async function updateAuto(field,value){const {data,error}=await supabase.from("media_autopilot").update({[field]:value,updated_at:new Date().toISOString()}).eq("id",1).select("*").single();if(error)return msg(error.message,true);autopilot=data;renderAutopilot()}$("autoMode").onchange=e=>updateAuto("mode",e.target.value);$("autoFrequency").onchange=e=>updateAuto("publishing_frequency",e.target.value);
async function boot(){try{const {data:{user}}=await supabase.auth.getUser();if(!user){$("loginPanel").hidden=false;$("adminPanel").hidden=true;return}if(!(await isAdmin())){$("loginPanel").hidden=false;$("adminPanel").hidden=true;loginMsg("This account is signed in but is not an authorized Jabari Media admin.");return}$("loginPanel").hidden=true;$("adminPanel").hidden=false;await loadCategories();await loadArticles();await loadTopics();await loadAutopilot()}catch(e){loginMsg(e.message||String(e))}}boot();