create extension if not exists pg_cron;
create extension if not exists pg_net;

create table if not exists public.media_promotions (
  id bigint generated by default as identity primary key,
  article_id bigint not null unique references public.media_articles(id) on delete cascade,
  target_count integer not null default 50 check (target_count > 0),
  successful_count integer not null default 0 check (successful_count >= 0),
  failed_count integer not null default 0 check (failed_count >= 0),
  status text not null default 'active' check (status in ('active','completed','stopped')),
  stop_reason text,
  completed_at timestamptz,
  stopped_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.media_promotion_recipients (
  id bigint generated by default as identity primary key,
  promotion_id bigint not null references public.media_promotions(id) on delete cascade,
  contact_id bigint not null references public.promoter_contacts(id) on delete cascade,
  status text not null default 'sending' check (status in ('sending','sent','failed')),
  attempts integer not null default 1,
  last_attempt_at timestamptz,
  sent_at timestamptz,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (promotion_id, contact_id)
);

create index if not exists media_promotions_status_idx on public.media_promotions(status, created_at);
create index if not exists media_promotion_recipients_promotion_idx on public.media_promotion_recipients(promotion_id, status);

alter table public.media_promotions enable row level security;
alter table public.media_promotion_recipients enable row level security;

-- The bot uses the Supabase service-role key, so no client-facing policies are needed here.

-- Run the Jabari worker every minute. The worker decides whether publishing is due
-- and independently processes active per-article promotions.
do $$
declare
  existing_job_id bigint;
begin
  select jobid into existing_job_id from cron.job where jobname = 'jabari-media-worker-every-minute' limit 1;
  if existing_job_id is not null then
    perform cron.unschedule(existing_job_id);
  end if;

  perform cron.schedule(
    'jabari-media-worker-every-minute',
    '* * * * *',
    $job$
      select net.http_post(
        url := 'https://jabari-promoter.onrender.com/automation-worker',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'x-jabari-worker-secret', (select worker_secret from public.media_worker_config where id = 1)
        ),
        body := '{}'::jsonb,
        timeout_milliseconds := 5000
      ) as request_id;
    $job$
  );
end $$;
